name: day_today
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  flutter_image_filters: ^0.0.17
  http_parser: ^4.0.2
  html: ^0.15.4
  gap: ^3.0.1
  lottie: ^3.1.0
  sign_button: ^2.0.6
  provider: ^6.1.2
  card_swiper: ^3.0.1
  flutter_carousel_widget: ^2.2.0
  like_button: ^2.0.5
  share_plus: ^8.0.3
  firebase_core: ^2.29.0
  custom_signin_buttons: ^1.0.2
  social_login_buttons: ^1.0.7
  chart_sparkline: ^1.0.15+1
  syncfusion_flutter_charts: ^25.1.39+1
  line_awesome_flutter: ^2.0.0
  dio: ^5.4.2+1
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  flutter_calendar_carousel: ^2.4.2
  googleapis_auth: ^1.1.0
  googleapis: ^13.1.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.19.2
  sign_in_with_apple: ^6.1.0
  the_apple_sign_in: ^1.1.1
  flutter_facebook_auth: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/logInAnimation.json
    - assets/animations/tickSucessfulAnimation.json
    - assets/animations/LoadingAnimation.json
    - assets/animations/newsAnimation.json
    - assets/images/facbookIcon.png
    - assets/images/
    - assets/images/currencies/
    - assets/images/wave1.png
    - assets/images/altNewsPoster.jpeg
    - assets/fonts/
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
    - family: LibreBaskerville-Regular
      fonts:
        - asset: assets/fonts/LibreBaskerville-Regular.ttf
    - family: stretch-pro
      fonts:
        - asset: assets/fonts/stretch-pro.regular.ttf
    - family: bronice-regular
      fonts:
        - asset: assets/fonts/bronice-regular.otf
    - family: apercu_regular_pro
      fonts:
        - asset: assets/fonts/apercu_regular_pro.otf
    - family: apercu_bold_pro
      fonts:
        - asset: assets/fonts/apercu_bold_pro.otf
    - family: Futura-Bold
      fonts:
        - asset: assets/fonts/Futura-Bold.ttf
    - family: Futura-Book
      fonts:
        - asset: assets/fonts/Futura-Book.ttf
    - family: Reality_Check
      fonts:
        - asset: assets/fonts/Reality_Check.otf
    - family: Poly
      fonts:
        - asset: assets/fonts/Poly-Regular.ttf
    - family: FKRomanStandard
      fonts:
        - asset: assets/fonts/FKRomanStandard.otf
    - family: CourierPrime
      fonts:
        - asset: assets/fonts/CourierPrime-Regular.ttf
    - family: PolySans
      fonts:
        - asset: assets/fonts/PolySans Neutral.ttf
      # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
